services:
  bot:
    image: popplebot:latest
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - svc
    networks:
      - popple
    env_file: .envrc

  svc:
    hostname: popplesvc
    image: popplesvc:latest
    build:
      context: .
      dockerfile: Dockerfile.svc
    depends_on:
      - db
    networks:
      - popple
    env_file: .envrc

  db:
    image: mysql:8.0
    hostname: poppledb
    volumes:
      - poppledata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - popple
    env_file: .envrc

networks:
  popple: {}

volumes:
  poppledata:
    external: true